### ISSUE TITLE
code does not work with files that have different number of total frames.

### ISSUE THREAD

**Issue by fahad-o** [cbraswe/video#11]
#last error trace
    
#   File "c:\Users\fahdA\Documents\HPC_Final_Project\video\code\avg_color_vectorized_no_append_decord_jn.py", line 81, in <module>
#     main()
#   File "c:\Users\fahdA\Documents\HPC_Final_Project\video\code\avg_color_vectorized_no_append_decord_jn.py", line 75, in main
#     avg_color_vectorized(vid_file, 1920, 1080, output)
#   File "c:\Users\fahdA\Documents\HPC_Final_Project\video\code\avg_color_vectorized_no_append_decord_jn.py", line 44, in avg_color_vectorized
#     frames_batch = vr.get_batch(range(slice_ind, slice_ind+num_frames_per_slice)).asnumpy()
#   File "C:\Users\fahdA\AppData\Local\Programs\Python\Python36\lib\site-packages\decord\video_reader.py", line 171, in get_batch
#     indices = _nd.array(self._validate_indices(indices))
#   File "C:\Users\fahdA\AppData\Local\Programs\Python\Python36\lib\site-packages\decord\video_reader.py", line 129, in _validate_indices
#     raise IndexError('Out of bound indices: {}'.format(indices[indices >= self._num_frame]))
# IndexError: Out of bound indices: [1439]

**Comment by fahad-o** [comment]
sorry forgot to remove the bound sign..

**Comment by cbraswe** [comment]
Hmm so is it busted still or no? I think I can fix it easily, as I had similar problems with other versions of the code. I had to introduce some conditional statements that I may not have properly wrote in when I did the indices.

**Comment by fahad-o** [comment]
still busted was just looking at it be my guest if you would like to fix it

**Comment by cbraswe** [comment]
i'll knab it first thing tomorrow because I think I can pretty quickly snub it out. that's my bad, i should have tested the logic on the other shorter video I have!

**Comment by fahad-o** [comment]
not sure about performance but having the code be in classes may be a good way to do the testing portion of it (we can use unit testing libraries).

**Comment by fahad-o** [comment]
I can do that in a few seconds if you would like.

**Comment by cbraswe** [comment]
Okay I found the bug pretty quick. I had a logic issue, and I had solid output on my end after I changed the error line. I fixed it in the .py file. I also love how you're structuring the .py file, and honestly - you don't need to ask me if I'd like anything. Just do it if you think it'll help us 🥇. I can't say I'm familiar with unit testing libraries, but I guess imma learn today!

**Comment by fahad-o** [comment]
> Okay I found the bug pretty quick. I had a logic issue, and I had solid output on my end after I changed the error line. I fixed it in the .py file. I also love how you're structuring the .py file, and honestly - you don't need to ask me if I'd like anything. Just do it if you think it'll help us 🥇. I can't say I'm familiar with unit testing libraries, but I guess imma learn today!

great, the question was in you as in the group. The thing about it is that it might make it harder for others to program if they are not familiar with classes so that is why I asked :)

**Comment by cbraswe** [comment]
> 
> 
> > Okay I found the bug pretty quick. I had a logic issue, and I had solid output on my end after I changed the error line. I fixed it in the .py file. I also love how you're structuring the .py file, and honestly - you don't need to ask me if I'd like anything. Just do it if you think it'll help us 🥇. I can't say I'm familiar with unit testing libraries, but I guess imma learn today!
> 
> great, the question was in you as in the group. The thing about it is that it might make it harder for others to program if they are not familiar with classes so that is why I asked :)

 @amirtofighi58 @earguel 

I'll toss in my vote as a 👍. I think it'll be fine, and it might be more preferable.
