### ISSUE TITLE
cv::imwrite_ error

### ISSUE THREAD

**Issue by fahad-o** [cbraswe/video#12]
Traceback (most recent call last):
  File \Documents\HPC_Final_Project\video\code\avg_color_vectorized_no_append_decord_jn.py", line 97, in <module>
    main()
  File "\Documents\HPC_Final_Project\video\code\avg_color_vectorized_no_append_decord_jn.py", line 91, in main
    avg_color_vectorized(vid_file, 1920, 1080, output)
  File "\Documents\HPC_Final_Project\video\code\avg_color_vectorized_no_append_decord_jn.py", line 57, in avg_color_vectorized
    cv2.imwrite(out_path, image.transpose(1,0,2))
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgcodecs\src\loadsave.cpp:667: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'

we may need to specify what version of python & libraries this code will work with.

**Comment by cbraswe** [comment]
I think this is a bit of an un-intuitive error - I think it's a lack of a file extension in the out_path being declared. So it's missing the .jpg or .png or maybe the OpenCV version doesn't support the specified file extension. 

If it's not that, I've got:
opencv-python==4.5.1.48
Python 3.7.6 (i'm going to take this to python 3.8.6 to match Bridges)

**Comment by fahad-o** [comment]
I have found the error and committed it you are correct I forgot that the output is an image not a .mp4 file..

**Comment by fahad-o** [comment]
> I think this is a bit of an un-intuitive error - I think it's a lack of a file extension in the out_path being declared. So it's missing the .jpg or .png or maybe the OpenCV version doesn't support the specified file extension.
> 
> If it's not that, I've got:
> opencv-python==4.5.1.48
> Python 3.7.6 (i'm going to take this to python 3.8.6 to match Bridges)

good idea checking if it runs on 3.8.6. Not sure if bridges will have those specific libraries.  or that python 3.8.6 will have a compatible version for them (in case we have the option of installing new libs to bridges).

**Comment by cbraswe** [comment]
We can install new python libraries via pip and even specific versions! As long as it's got a pip install, it'll work. Bridges does have both Python 2 (no thank you) and Python 3, but I honestly think we may be limited to like Python 3.8.6 and not have every version available.
