### ISSUE TITLE
check if in bridges we can install new libraries.

### ISSUE THREAD

**Issue by cbraswe** [cbraswe/video#14]
Bridges and Numba are lacking compatibility.

**Comment by cbraswe** [comment]
[cbraswe@bridges2-login013 code]$ python3
Python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/__init__.py", line 39, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/extending.py", line 18, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/pythonapi.py", line 13, in <module>
    from numba.core import (
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/lowering.py", line 12, in <module>
    from numba.core.environment import Environment
  File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/environment.py", line 3, in <module>
    from numba import _dynfunc
ImportError: /jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/_dynfunc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_IsFinalizing
>>>

**Comment by fahad-o** [comment]
> Was testing modules after installation by running python3 interactively using CLI. import numba fails
> 
> [cbraswe@bridges2-login013 code]$ python3
> Python 3.6.8 (default, Apr 16 2020, 01:36:27)
> [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import numba
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/**init**.py", line 39, in 
> > > > from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/decorators.py", line 12, in 
> > > > from numba.stencils.stencil import stencil
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/stencils/stencil.py", line 11, in 
> > > > from numba.core import types, typing, utils, ir, config, ir_utils, registry
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/ir_utils.py", line 16, in 
> > > > from numba.core.extending import _Intrinsic
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/extending.py", line 18, in 
> > > > from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/pythonapi.py", line 13, in 
> > > > from numba.core import (
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/lowering.py", line 12, in 
> > > > from numba.core.environment import Environment
> > > > File "/jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/core/environment.py", line 3, in 
> > > > from numba import _dynfunc
> > > > ImportError: /jet/home/cbraswe/.local/lib/python3.6/site-packages/numba/_dynfunc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_IsFinalizing

Check this out
https://github.com/PyAV-Org/PyAV/issues/348

**Comment by fahad-o** [comment]
the possible solution is building from source

**Comment by cbraswe** [comment]
Agreed, bridges also seems to have a secondary error I'm working out now... This issue might be the root cause.

If I use module load python/3.8.6 (instructions per bridges), it can't access any of the installed modules. However, if I don't load a module and instead just use python3 and pip3 for various calls, I can access the modules successfully.

**Comment by fahad-o** [comment]
> Agreed, bridges also seems to have a secondary error I'm working out now... This issue might be the root cause.
> 
> If I use module load python/3.8.6 (instructions per bridges), it can't access any of the installed modules. However, if I don't load a module and instead just use python3 and pip3 for various calls, I can access the modules successfully.

Could you document your efforts in case someone needed to run it? I suggest a new folder with .txt files for each error trace -solution.

**Comment by cbraswe** [comment]
Will do!

**Comment by cbraswe** [comment]
Okay, I got my first success with Numba. Using numba==0.47.0 and llvmlite==31.0. I am going to try a more recent version of both libraries now.

**Comment by cbraswe** [comment]
CV2 does not work, working this now.

**Comment by cbraswe** [comment]
AND SUCCESS. I am going to have to do a write-up on the wiki because there are a lot of surprising errors on this, and it is very finicky.

To fix CV2, I had to use module unload intel and load module load GCC. It seemed to need something related  to a GNU compiler. That was a wild ride.

**Comment by fahad-o** [comment]
> AND SUCCESS. I am going to have to do a write-up on the wiki because there are a lot of surprising errors on this, and it is very finicky.
> 
> To fix CV2, I had to use module unload intel and load module load GCC. It seemed to need something related to a GNU compiler. That was a wild ride.

Good Job!
